import type { ColumnDefinitions, MigrationBuilder } from 'node-pg-migrate';

export const shorthands: ColumnDefinitions | undefined = undefined;

export async function up(pgm: MigrationBuilder): Promise<void> {
  pgm.sql(`
    DO $$
    DECLARE
      next_id integer;
    BEGIN
      SELECT COALESCE(MAX(id), 0) + 1 INTO next_id FROM players;
      EXECUTE format('ALTER TABLE players ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)', next_id);
    END $$;
  `);
}

export async function down(pgm: MigrationBuilder): Promise<void> {
  pgm.sql(`ALTER TABLE players ALTER COLUMN id DROP IDENTITY IF EXISTS;`);
}
